### ISSUE TITLE
Bakgrunnsbilde

### ISSUE THREAD

**Issue by Assios** [stianjensen/shortsdag.no#1]
Burde kanskje vise et annet bilde når det ikke er shortsdag?

**Comment by stianjensen** [comment]
Lurt. Hva med https://unsplash.com/photos/x8xsbx4zfYs ?

**Comment by Assios** [comment]
Den er bra, men det er jo ikke sikkert det regner selv om det ikke er shortsdag. Hva med forskjellige bilder for regn, kaldt, snø og shortsdag!?

**Comment by stianjensen** [comment]
Hmm, hvordan ser kaldt ut? (uten snø)

**Comment by sigvef** [comment]
![image](https://cloud.githubusercontent.com/assets/578029/15130902/23b6a842-164c-11e6-81da-3cc4895e2864.png)

**Comment by stianjensen** [comment]
Kan ta dette for snø: https://unsplash.com/photos/ke-sGAA8w64
Dette for regn: https://unsplash.com/photos/p_HYA_T-1WU
Og dette for kaldt: https://unsplash.com/photos/T8gLom6k8Jo

**Comment by Assios** [comment]
Den er bra, blir helt frysen her jeg sitter på do!

**Comment by cristeahub** [comment]
What about something like this as a replacement for the boy? ![](http://3.bp.blogspot.com/-YdX5waXywDk/UQqxlAS4erI/AAAAAAAAAUw/5gWfSVDwkv4/s1600/freezing%2Bcold.jpg)
