### ISSUE TITLE
Shortsdag true/false i API

### ISSUE THREAD

**Issue by draperunner** [stianjensen/shortsdag.no#2]
Hei!

Kunne det vore ein idé å få eit ja/nei-svar frå APIet om det er shortsdag i dag eller ikkje? Altså at svaret algoritmen din i scripts.js gir, er mogleg å få tak i gjennom APIet.

**Comment by stianjensen** [comment]
Jepp.

Kan legge det inn i tillegg til det som er no, slik at ein kan velje om ein vil følge den offisielle shortsdag-meldinga, eller bruke dataen til å berekne si eiga shortsdag-melding.
